import type { ShipClassStatus, CharacterClass, SkillDefinition, ClassName, ShopItem } from './types';

export const SHIP_NAME_PART1 = ["IAGO", "HECATE", "OBERON", "WHITEHALL", "DUNCAN", "BANQUO", "WINTER", "MARLOWE", "TEMPEST", "FAUST"];
export const SHIP_NAME_PART2 = ["VALEFOR", "OPHANIM", "MARAX", "MARINER", "LABOLAS", "ASTAROTH", "CHERUBIM", "TYRANT", "BALAAM", "MURMUR"];
export const SHIP_NAME_PART3 = ["ECHO", "ALPHA", "OMEGA", "KING", "BEGGAR", "DELTA", "EPSILON", "JIBRIL", "BRAVO", "TANGO"];


export const SHIP_CLASS_STATUS: ShipClassStatus[] = [
    { range: [0, 0], class: 'Colony Ship', status: 'Habitable (Functioning)', survivors: 'Survivors', systems: 'Stable Engine, Thrusters, Jump Drive', salvage: [{dice: '1d10', item: 'Cryopods'}, {dice: '1d100', item: 'Trade Units'}, {dice: '2d10', item: 'Survivors'}] },
    { range: [1, 9], class: 'Mining Frigate', status: 'Uninhabitable', survivors: 'No Survivors', systems: 'Engine, Thrusters, Jump Drive non-functioning', salvage: [{dice: '2d100', item: 'Scrap'}, {dice: '4d10', item: 'Ore'}, {dice: '1d10', item: 'Fuel Units'}] },
    { range: [10, 19], class: 'Mining Frigate', status: 'Uninhabitable', survivors: 'No Survivors', systems: 'Engine, Thrusters, Jump Drive non-functioning', salvage: [{dice: '2d100', item: 'Scrap'}, {dice: '4d10', item: 'Ore'}, {dice: '1d10', item: 'Fuel Units'}] },
    { range: [20, 24], class: 'Mining Frigate', status: 'Uninhabitable', survivors: 'No Survivors', systems: 'Engine, Thrusters, Jump Drive non-functioning', salvage: [{dice: '2d100', item: 'Scrap'}, {dice: '4d10', item: 'Ore'}, {dice: '1d10', item: 'Fuel Units'}] },
    { range: [25, 29], class: 'Freighter', status: 'Uninhabitable', survivors: 'No Survivors', systems: 'Engine, Thrusters, Jump Drive non-functioning', salvage: [{dice: '1d10', item: 'Fuel Units'}, {dice: '3d10', item: 'Metal'}]},
    { range: [30, 34], class: 'Freighter', status: 'Uninhabitable', survivors: 'No Survivors', systems: 'Engine, Thrusters, Jump Drive non-functioning', salvage: [{dice: '1d10', item: 'Fuel Units'}, {dice: '3d10', item: 'Metal'}]},
    { range: [35, 39], class: 'Freighter', status: 'Uninhabitable', survivors: 'No Survivors', systems: 'Engine, Thrusters, Jump Drive non-functioning', salvage: [{dice: '1d10', item: 'Fuel Units'}, {dice: '3d10', item: 'Metal'}]},
    { range: [40, 44], class: 'Freighter', status: 'Uninhabitable', survivors: 'No Survivors', systems: 'Engine, Thrusters, Jump Drive non-functioning', salvage: [{dice: '1d10', item: 'Fuel Units'}, {dice: '3d10', item: 'Metal'}]},
    { range: [45, 49], class: 'Freighter', status: 'Uninhabitable', survivors: 'No Survivors', systems: 'Engine, Thrusters, Jump Drive non-functioning', salvage: [{dice: '1d10', item: 'Fuel Units'}, {dice: '3d10', item: 'Metal'}]},
    { range: [50, 54], class: 'Freighter', status: 'Uninhabitable', survivors: 'No Survivors', systems: 'Engine, Thrusters, Jump Drive non-functioning', salvage: [{dice: '1d10', item: 'Fuel Units'}, {dice: '3d10', item: 'Metal'}]},
    { range: [55, 57], class: 'Shuttle', status: 'Uninhabitable', survivors: 'No Survivors', systems: 'Engine, Thrusters, Jump Drive non-functioning', salvage: [{dice: '1d10', item: 'Fuel Units'}, {dice: '3d10', item: 'Metal'}]},
    { range: [58, 60], class: 'Shuttle', status: 'Uninhabitable', survivors: 'No Survivors', systems: 'Engine, Thrusters, Jump Drive non-functioning', salvage: [{dice: '1d10', item: 'Fuel Units'}, {dice: '3d10', item: 'Metal'}]},
    { range: [61, 63], class: 'Shuttle', status: 'Uninhabitable', survivors: 'No Survivors', systems: 'Engine, Thrusters, Jump Drive non-functioning', salvage: [{dice: '1d10', item: 'Fuel Units'}, {dice: '3d10', item: 'Metal'}]},
    { range: [64, 66], class: 'Courier', status: 'Uninhabitable', survivors: 'No Survivors', systems: 'Engine, Thrusters, Jump Drive non-functioning', salvage: [{dice: '2d10', item: 'Galley Stock'}]},
    { range: [67, 69], class: 'Courier', status: 'Uninhabitable', survivors: 'No Survivors', systems: 'Engine, Thrusters, Jump Drive non-functioning', salvage: [{dice: '2d10', item: 'Galley Stock'}]},
    { range: [70, 71], class: 'Courier', status: 'Uninhabitable', survivors: 'No Survivors', systems: 'Engine, Thrusters, Jump Drive non-functioning', salvage: [{dice: '2d10', item: 'Galley Stock'}]},
    { range: [72, 73], class: 'Courier', status: 'Uninhabitable', survivors: 'No Survivors', systems: 'Engine, Thrusters, Jump Drive non-functioning', salvage: [{dice: '2d10', item: 'Galley Stock'}]},
    { range: [74, 75], class: 'Courier', status: 'Uninhabitable', survivors: 'No Survivors', systems: 'Engine, Thrusters, Jump Drive non-functioning', salvage: [{dice: '2d10', item: 'Galley Stock'}]},
    { range: [76, 77], class: 'Courier', status: 'Uninhabitable', survivors: 'No Survivors', systems: 'Engine, Thrusters, Jump Drive non-functioning', salvage: [{dice: '2d10', item: 'Galley Stock'}]},
    { range: [78, 79], class: 'Research Vessel', status: 'Habitable (Non-Functioning)', survivors: 'No Survivors', systems: 'Stable Engine, Thrusters, Jump Drive', salvage: [{dice: '1d100', item: 'Trade Units of Random Cargo'}, {dice: '1d10', item: 'Cryopods'}]},
    { range: [80, 80], class: 'Research Vessel', status: 'Habitable (Non-Functioning)', survivors: 'No Survivors', systems: 'Stable Engine, Thrusters, Jump Drive', salvage: [{dice: '1d100', item: 'Trade Units of Random Cargo'}, {dice: '1d10', item: 'Cryopods'}]},
    { range: [81, 81], class: 'Research Vessel', status: 'Habitable (Non-Functioning)', survivors: 'No Survivors', systems: 'Stable Engine, Thrusters, Jump Drive', salvage: [{dice: '1d100', item: 'Trade Units of Random Cargo'}, {dice: '1d10', item: 'Cryopods'}]},
    { range: [82, 82], class: 'Blockade Runner', status: 'Habitable (Non-Functioning)', survivors: 'No Survivors', systems: 'Stable Engine, Thrusters, Jump Drive', salvage: [{dice: '1d10', item: 'Precious Metal'}, {dice: '1d1', item: 'Medbay'}]},
    { range: [83, 83], class: 'Blockade Runner', status: 'Habitable (Non-Functioning)', survivors: 'No Survivors', systems: 'Stable Engine, Thrusters, Jump Drive', salvage: [{dice: '1d10', item: 'Precious Metal'}, {dice: '1d1', item: 'Medbay'}]},
    { range: [84, 84], class: 'Cutter', status: 'Habitable (Non-Functioning)', survivors: 'No Survivors', systems: 'Stable Engine, Thrusters, Jump Drive', salvage: [{dice: '1d1', item: 'Weapon'}, {dice: '1d10', item: 'Precious Metal'}]},
    { range: [85, 85], class: 'Cutter', status: 'Habitable (Non-Functioning)', survivors: 'No Survivors', systems: 'Stable Engine, Thrusters, Jump Drive', salvage: [{dice: '1d1', item: 'Weapon'}, {dice: '1d10', item: 'Precious Metal'}]},
    { range: [86, 86], class: 'Cutter', status: 'Habitable (Non-Functioning)', survivors: 'No Survivors', systems: 'Stable Engine, Thrusters, Jump Drive', salvage: [{dice: '1d1', item: 'Weapon'}, {dice: '1d10', item: 'Precious Metal'}]},
    { range: [87, 87], class: 'Troopship', status: 'Habitable (Non-Functioning)', survivors: '2d10 Survivors (In Cryosleep)', systems: 'Stable Engine, Thrusters, Jump Drive', salvage: [{dice: '1d10', item: 'Contraband'}, {dice: '1d1', item: 'Computer'}]},
    { range: [88, 88], class: 'Troopship', status: 'Habitable (Non-Functioning)', survivors: '2d10 Survivors (In Cryosleep)', systems: 'Stable Engine, Thrusters, Jump Drive', salvage: [{dice: '1d10', item: 'Contraband'}, {dice: '1d1', item: 'Computer'}]},
    { range: [89, 89], class: 'Troopship', status: 'Habitable (Non-Functioning)', survivors: '2d10 Survivors (In Cryosleep)', systems: 'Stable Engine, Thrusters, Jump Drive', salvage: [{dice: '1d10', item: 'Contraband'}, {dice: '1d1', item: 'Computer'}]},
    { range: [90, 90], class: 'Colony Ship', status: 'Habitable (Functioning)', survivors: 'Survivors', systems: 'Jump Drive', salvage: [{dice: '1d1', item: 'Jump Drive'}, {dice: '1d1', item: 'Unstable Core'}]},
    { range: [91, 91], class: 'Colony Ship', status: 'Habitable (Functioning)', survivors: 'Survivors', systems: 'Jump Drive', salvage: [{dice: '1d1', item: 'Jump Drive'}, {dice: '1d1', item: 'Unstable Core'}]},
    { range: [92, 92], class: 'Colony Ship', status: 'Habitable (Functioning)', survivors: 'Survivors', systems: 'Jump Drive', salvage: [{dice: '1d1', item: 'Jump Drive'}, {dice: '1d1', item: 'Unstable Core'}]},
    { range: [93, 93], class: 'Colony Ship', status: 'Habitable (Functioning)', survivors: 'Survivors', systems: 'Jump Drive', salvage: [{dice: '1d1', item: 'Jump Drive'}, {dice: '1d1', item: 'Unstable Core'}]},
    { range: [94, 94], class: 'Colony Ship', status: 'Habitable (Functioning)', survivors: 'Survivors', systems: 'Jump Drive', salvage: [{dice: '1d1', item: 'Jump Drive'}, {dice: '1d1', item: 'Unstable Core'}]},
    { range: [95, 95], class: 'Colony Ship', status: 'Habitable (Functioning)', survivors: 'Survivors', systems: 'Jump Drive', salvage: [{dice: '1d1', item: 'Jump Drive'}, {dice: '1d1', item: 'Unstable Core'}]},
    { range: [96, 96], class: 'Colony Ship', status: 'Habitable (Functioning)', survivors: 'Survivors', systems: 'Jump Drive', salvage: [{dice: '1d1', item: 'Jump Drive'}, {dice: '1d1', item: 'Unstable Core'}]},
    { range: [97, 97], class: 'Colony Ship', status: 'Habitable (Functioning)', survivors: 'Survivors', systems: 'Jump Drive', salvage: [{dice: '1d1', item: 'Jump Drive'}, {dice: '1d1', item: 'Unstable Core'}]},
    { range: [98, 98], class: 'Colony Ship', status: 'Habitable (Functioning)', survivors: 'Survivors', systems: 'Jump Drive', salvage: [{dice: '1d1', item: 'Jump Drive'}, {dice: '1d1', item: 'Unstable Core'}]},
    { range: [99, 99], class: 'Colony Ship', status: 'Habitable (Functioning)', survivors: 'Survivors', systems: 'Jump Drive', salvage: [{dice: '1d1', item: 'Jump Drive'}, {dice: '1d1', item: 'Unstable Core'}]},
];

export const CAUSE_OF_RUINATION = [ "Virus", "Combat", "Raided by Pirates", "Hyperspace Malfunction", "Abandoned Ship", "Insane AI", "Mutiny", "Crash: Other Ship", "Crash: Space Debris", "Crash: Jump Drive Miscalculation", "Engine Failure", "Cannibalism", "Nerve Gas", "Escape Pod Never Returned", "Betrayal/Backstabbing", "Succumbed to Nightmares", "Hatch Opened, No Air", "Cargo Created Mishap", "Starvation", "Part of a Conspiracy", "Thrusters Slagged", "Weapons System Malfunction", "Cryosleep Never Disengaged", "Complex Series of Events", "Suicide Pact", "Parasite Infestation", "Environmental Systems Failure", "Uncontrollable Fire", "Failed Fraud Attempt", "Void Worshipping", "Bizarre Love Triangle", "Fight Spiraled Out of Control", "Chainsaw Rampage", "Drug Addled Debauchery", "Fatal Depressurization", "Nightmares Ending in Heart Attack", "Mob Hit", "Crew Members Vanished", "Prank Taken Too Far", "William Tell Trick", "Virus", "Combat", "Raided by Pirates", "Hyperspace Malfunction", "Abandoned Ship", "Insane AI", "Mutiny", "Crash: Other Ship", "Crash: Space Debris", "Crash: Jump Drive Miscalculation", "Engine Failure", "Cannibalism", "Nerve Gas", "Escape Pod Never Returned", "Betrayal/Backstabbing", "Succumbed to Nightmares", "Hatch Opened, No Air", "Cargo Created Mishap", "Starvation", "Part of a Conspiracy", "Thrusters Slagged", "Weapons System Malfunction", "Cryosleep Never Disengaged", "Complex Series of Events", "Suicide Pact", "Parasite Infestation", "Environmental Systems Failure", "Uncontrollable Fire", "Failed Fraud Attempt", "Void Worshipping", "Bizarre Love Triangle", "Fight Spiraled Out of Control", "Chainsaw Rampage", "Drug Addled Debauchery", "Fatal Depressurization", "Nightmares Ending in Heart Attack", "Mob Hit", "Crew Members Vanished", "Prank Taken Too Far", "William Tell Trick", "Virus", "Combat", "Raided by Pirates", "Hyperspace Malfunction", "Abandoned Ship", "Insane AI", "Mutiny", "Crash: Other Ship", "Crash: Space Debris", "Crash: Jump Drive Miscalculation", "Engine Failure", "Cannibalism", "Nerve Gas", "Escape Pod Never Returned", "Betrayal/Backstabbing", "Succumbed to Nightmares", "Hatch Opened, No Air", "Cargo Created Mishap", "Starvation", "Part of a Conspiracy", "Thrusters Slagged", "Weapons System Malfunction", "Cryosleep Never Disengaged", "Complex Series of Events" ];
export const WEIRD = [ "Haunted", "Inhabited by Alien Life", "Terraformed by Strange Creatures", "Crew Dressed for Costume Party", "Crew All Identical", "Crew was preparing Theatrical Performance", "Morbid Artwork", "Pet Hoarders", "Erotic Sculptures", "Communist Regalia", "Company Uniform", "Cult Members", "Extensive Journals Kept", "Strange Health Obsession", "Unnervingly Clean", "Android was Poisoning Captain", "Ancient Ship", "Temporal Distortions", "Failed Utopia", "Crew Weighed and Measured Weekly", "Extensive Body Modification", "Isolated Physics Anomalies", "Sexual Deviants", "Religious Extremists", "Transhumanist Android Worshippers", "Anti-Android Conspiracists", "Nauseating Stench", "Everything is Jury-Rigged", "Crew Taking Video Through the Catastrophe", "Body Horror", "Scooby-Doo Crew", "Interior Coated in Flesh, Doors are Membranes", "Whispering Echoes Always a Room Ahead", "Dolls in Macabre Tableaux", "Dead Crew: Exploded Heads", "Elaborately Posed Corpses (Hooks & Chains)", "Flickering Lights and Frenzied Screams", "Ship Rearranges Itself Frequently", "Ship Has Infinite Depth", "Fruit Basket, Greeting Card Inexplicably Addressed to Crew", "Haunted", "Inhabited by Alien Life", "Terraformed by Strange Creatures", "Crew Dressed for Costume Party", "Crew All Identical", "Crew was preparing Theatrical Performance", "Morbid Artwork", "Pet Hoarders", "Erotic Sculptures", "Communist Regalia", "Company Uniform", "Cult Members", "Extensive Journals Kept", "Strange Health Obsession", "Unnervingly Clean", "Android was Poisoning Captain", "Ancient Ship", "Temporal Distortions", "Failed Utopia", "Crew Weighed and Measured Weekly", "Extensive Body Modification", "Isolated Physics Anomalies", "Sexual Deviants", "Religious Extremists", "Transhumanist Android Worshippers", "Anti-Android Conspiracists", "Nauseating Stench", "Everything is Jury-Rigged", "Crew Taking Video Through the Catastrophe", "Body Horror", "Scooby-Doo Crew", "Interior Coated in Flesh, Doors are Membranes", "Whispering Echoes Always a Room Ahead", "Dolls in Macabre Tableaux", "Dead Crew: Exploded Heads", "Elaborately Posed Corpses (Hooks & Chains)", "Flickering Lights and Frenzied Screams", "Ship Rearranges Itself Frequently", "Ship Has Infinite Depth", "Fruit Basket, Greeting Card Inexplicably Addressed to Crew", "Haunted", "Inhabited by Alien Life", "Terraformed by Strange Creatures", "Crew Dressed for Costume Party", "Crew All Identical", "Crew was preparing Theatrical Performance", "Morbid Artwork", "Pet Hoarders", "Erotic Sculptures", "Communist Regalia", "Company Uniform", "Cult Members", "Extensive Journals Kept", "Strange Health Obsession", "Unnervingly Clean", "Android was Poisoning Captain", "Ancient Ship", "Temporal Distortions" ];
export const CARGO_TYPE = [ "Body Bags (Full)", "Wine", "Wine", "Wine", "Wine", "Wine", "Wine", "Wine", "Wine", "Wine", "Complex Navigational Equipment", "Complex Navigational Equipment", "Complex Navigational Equipment", "Complex Navigational Equipment", "Complex Navigational Equipment", "Complex Navigational Equipment", "Complex Navigational Equipment", "Complex Navigational Equipment", "Complex Navigational Equipment", "Complex Navigational Equipment", "Ceramics", "Ceramics", "Ceramics", "Ceramics", "Ceramics", "Antique Books", "Antique Books", "Antique Books", "Antique Books", "Antique Books", "Garden Gnomes (Full of Illegal Stimulants)", "Garden Gnomes (Full of Illegal Stimulants)", "Garden Gnomes (Full of Illegal Stimulants)", "Garden Gnomes (Full of Illegal Stimulants)", "Garden Gnomes (Full of Illegal Stimulants)", "Opium", "Opium", "Opium", "Opium", "Opium", "Tea", "Tea", "Tea", "Tea", "Tea", "Silver Bars", "Silver Bars", "Silver Bars", "Silver Bars", "Silver Bars", "Sensitive Documents", "Sensitive Documents", "Sensitive Documents", "Sensitive Documents", "Sensitive Documents", "Anthropology Mission", "Anthropology Mission", "Anthropology Mission", "Botanists/Horticulturists", "Botanists/Horticulturists", "Botanists/Horticulturists", "Industrial Engineers/Architects", "Industrial Engineers/Architects", "Industrial Engineers/Architects", "Terraforming Equipment", "Terraforming Equipment", "Terraforming Equipment", "Hydroponic Plants", "Hydroponic Plants", "Hydroponic Plants", "Rare Wood", "Rare Wood", "Lab Rats", "Lab Rats", "Cultured Cells", "Cultured Cells", "Cremains", "Cremains", "Drug Production Starter Equipment", "Drug Production Starter Equipment", "Common Cloth", "Designer Clothes", "Expensive Fish (food)", "Pets", "Plastic Junk (gewgaws)", "Legionaries (guns & ammo)", "Religious Pilgrims (religious texts & symbols)", "Compressed Algae Blocks", "Disarmed ordinance (lack detonators)", "Cars (high end)", "Medicine", "Cosmetics", "Race Horse Reproductive Material", "Livestock", "Prisoners", "Mobile Black Site", "Census Takers", "Cadmium", "Preserved Fruit", "Refugees" ];

// CHARACTER CREATION CONSTANTS

export const FIRST_NAMES = ["Jax", "Kira", "Zane", "Cora", "Rhys", "Lena", "Milo", "Suri", "Finn", "Orion", "Anya", "Nico", "Zara", "Silas", "Esme"];
export const LAST_NAMES = ["Kade", "Vance", "Orlov", "Chen", "Rios", "Sato", "Khan", "Beckett", "Ito", "Volkov", "Moreau", "Janssen", "Valerius", "Singh"];
export const PRONOUNS = ["they/them", "she/her", "he/him"];


export const CLASSES_DATA: CharacterClass[] = [
    {
        name: 'Marine',
        description: 'Trained soldiers, experts in combat and survival. They are tough but their panic can be contagious.',
        stats_mods: { combat: 10 },
        saves_mods: { fear: 20, body: 10 },
        max_wounds_mod: 1,
        starting_skills: ['Military Training', 'Athletics'],
        bonus_skills: { trained: 2, expert: 1, master: 0 },
        trauma_response: 'Whenever you Panic, every close friendly player must make a Fear Save.'
    },
    {
        name: 'Android',
        description: 'Synthetic beings with superior intellect and resilience to fear, but often at the cost of social graces and physical prowess.',
        stats_mods: { intellect: 20 },
        saves_mods: { fear: 60 },
        max_wounds_mod: 1,
        starting_skills: ['Linguistics', 'Computers', 'Mathematics'],
        bonus_skills: { trained: 2, expert: 1, master: 0 },
        trauma_response: 'Fear Saves made by close friendly players are at Disadvantage.'
    },
    {
        name: 'Scientist',
        description: "Experts in research and analysis. Their deep knowledge can be a boon, or a source of great stress when they uncover things not meant for mortal minds.",
        stats_mods: { intellect: 10 },
        saves_mods: { sanity: 30 },
        max_wounds_mod: 0,
        starting_skills: [], // Pick 3 from a list
        bonus_skills: { trained: 2, expert: 1, master: 1 },
        trauma_response: 'Whenever you fail a Sanity Save, all close friendly players gain 1 Stress.'
    },
    {
        name: 'Teamster',
        description: 'Hard-working space haulers and engineers. They are reliable and versatile, capable of handling industrial equipment and enduring hardships.',
        stats_mods: { strength: 5, speed: 5, intellect: 5, combat: 5 },
        saves_mods: { sanity: 10, fear: 10, body: 10 },
        max_wounds_mod: 0,
        starting_skills: ['Industrial Equipment', 'Zero-G'],
        bonus_skills: { trained: 1, expert: 1, master: 0 },
        trauma_response: 'Once per session, you may take Advantage on a Panic Check.'
    }
];

export const SCIENTIST_SKILL_CHOICES = ['Biology', 'Geology', 'Computers', 'Mathematics', 'Chemistry', 'Industrial Equipment'];

export const ALL_SKILLS: SkillDefinition[] = [
    // Trained
    { name: 'Linguistics', description: 'Fluency in multiple languages and understanding of communication structures.', effects: 'Allows Intellect checks to understand, read, or speak unfamiliar languages.' },
    { name: 'Biology', description: 'The study of life and living organisms, both terrestrial and xeno.', effects: 'Allows Intellect checks to identify species, understand ecosystems, or analyze biological samples.' },
    { name: 'First Aid', description: 'Emergency medical care for injuries and ailments.', effects: 'Allows Intellect checks to stabilize dying characters and treat minor wounds.' },
    { name: 'Geology', description: 'Knowledge of planets, moons, asteroids and their mineral composition.', effects: 'Allows Intellect checks to identify valuable minerals and understand planetary phenomena.' },
    { name: 'Zero-G', description: 'Proficiency in maneuvering and working in a weightless environment.', effects: 'Allows Speed checks to navigate in zero-gravity. Without this skill, all movement checks in Zero-G are at Disadvantage.' },
    { name: 'Scavenging', description: 'The knack for finding useful items and resources from refuse and wreckage.', effects: 'Allows Intellect checks to find specific items or extra resources when searching an area.' },
    { name: 'Industrial Equipment', description: 'Familiarity with operating heavy machinery like forklifts, mag-clamps, and mining drills.', effects: 'Allows Speed checks to operate industrial hardware safely and effectively.' },
    { name: 'Computers', description: 'Competence in using standard computer systems and networks.', effects: 'Allows Intellect checks to access, bypass, or control computer systems and retrieve data.' },
    { name: 'Mechanical Repair', description: 'The ability to diagnose and fix common mechanical problems in equipment and vehicles.', effects: 'Allows Intellect checks to repair damaged machinery. Grants Advantage on jury-rigging.' },
    { name: 'Piloting', description: 'Skill in operating spacecraft and other vehicles.', effects: 'Allows Speed checks to pilot ships and vehicles, especially during complex maneuvers.' },
    { name: 'Mathematics', description: 'Advanced understanding of numbers, logic, and abstract systems.', effects: 'Allows Intellect checks to solve complex logical problems, calculate trajectories, and break simple codes.' },
    { name: 'Art', description: 'Ability in a creative field, such as painting, music, or writing.', effects: 'Allows for the creation of works that can influence morale or communicate complex ideas.' },
    { name: 'Archaeology', description: 'The study of ancient and alien cultures through their material remains.', effects: 'Allows Intellect checks to identify the purpose of ancient artifacts and understand alien ruins.' },
    { name: 'Theology', description: 'Knowledge of religions, cults, and belief systems, both human and xeno.', effects: 'Allows Intellect checks to understand religious motivations, rituals, and hierarchies.' },
    { name: 'Military Training', description: 'Basic knowledge of military conduct, chain of command, and procedures.', effects: 'Allows Intellect checks to understand military orders and tactics. Grants knowledge of military protocol.' },
    { name: 'Rimwise', description: 'Street-smarts and familiarity with the customs of outer rim colonies and fringe societies.', effects: 'Allows Intellect checks to gather rumors, find black markets, and avoid social faux pas on the fringe.' },
    { name: 'Athletics', description: 'Proficiency in physical activities like running, climbing, and jumping.', effects: 'Allows Strength or Speed checks for physical exertion. Grants Advantage on checks to escape grapples.' },
    { name: 'Chemistry', description: 'Understanding of chemical substances and their properties.', effects: 'Allows Intellect checks to analyze unknown substances, synthesize simple compounds, or identify poisons.' },
    // Expert
    { name: 'Psychology', description: 'The study of the mind and behavior.', effects: 'Allows Intellect checks to discern motives, detect lies, or provide basic counseling to reduce Stress.', prerequisites: ['Linguistics'] },
    { name: 'Genetics', description: 'In-depth knowledge of heredity, DNA, and biological variation.', effects: 'Allows Intellect checks to operate gene-sequencing equipment or identify genetic modifications.', prerequisites: ['Biology'] },
    { name: 'Pathology', description: 'The study and diagnosis of disease.', effects: 'Allows Intellect checks to identify diseases, causes of death, and vulnerabilities of alien organisms.', prerequisites: ['First Aid'] },
    { name: 'Botany', description: 'The scientific study of plant life, including alien flora.', effects: 'Allows Intellect checks to identify edible or dangerous plants and cultivate them.', prerequisites: ['Biology'] },
    { name: 'Planetology', description: 'Advanced study of planetary systems, atmospheres, and ecosystems.', effects: 'Allows Intellect checks to predict weather patterns and identify safe zones on alien worlds.', prerequisites: ['Geology'] },
    { name: 'Asteroid Mining', description: 'Specialized knowledge in extracting resources from asteroids.', effects: 'Grants Advantage on checks related to operating mining equipment and identifying rich deposits.', prerequisites: ['Zero-G'] },
    { name: 'Jury-Rigging', description: 'The art of making makeshift repairs with limited resources.', effects: 'Allows an Intellect check to temporarily fix complex equipment or create a one-use item.', prerequisites: ['Scavenging'] },
    { name: 'Engineering', description: 'The design, building, and maintenance of complex systems and structures.', effects: 'Allows Intellect checks to design new equipment or oversee major repairs to a starship.', prerequisites: ['Industrial Equipment'] },
    { name: 'Hacking', description: 'Unauthorized access to secure computer systems.', effects: 'Allows an opposed Intellect check to gain unauthorized access to secure systems and manipulate their data.', prerequisites: ['Computers'] },
    { name: 'Vehicle Specialization', description: 'Mastery of a specific class of vehicle (e.g., ground transport, fighter).', effects: 'Grants Advantage on all checks made to pilot or repair a specific type of vehicle.', prerequisites: ['Mechanical Repair'] },
    { name: 'Astrogation', description: 'The science of navigating a spacecraft through interstellar space.', effects: 'Allows Intellect checks to plot hyperspace jumps. Failure can lead to being lost in space.', prerequisites: ['Piloting'] },
    { name: 'Physics', description: 'Deep understanding of matter, energy, and the fundamental forces of the universe.', effects: 'Allows Intellect checks to understand strange physical phenomena or weaponize scientific equipment.', prerequisites: ['Mathematics'] },
    { name: 'Mysticism', description: 'Understanding of spiritual or esoteric beliefs that may touch upon reality.', effects: 'Allows Sanity Saves to resist certain supernatural horrors or understand esoteric texts.', prerequisites: ['Archaeology'] },
    { name: 'Tactics', description: 'The art of maneuvering military forces in combat.', effects: 'Allows Intellect checks to gain a tactical advantage in combat, such as a surprise round or superior positioning.', prerequisites: ['Theology'] },
    { name: 'Gunnery', description: 'Operation of starship-grade weaponry.', effects: 'Allows Combat checks to fire ship-to-ship weapons accurately.', prerequisites: ['Military Training'] },
    { name: 'Firearms', description: 'Proficiency with a wide range of personal ranged weapons.', effects: 'Allows Combat checks with ranged weapons. Without this skill, you have Disadvantage on all firearm attacks.', prerequisites: ['Rimwise'] },
    { name: 'Hand-to-Hand Combat', description: 'Trained in unarmed and melee combat.', effects: 'Allows Combat checks for melee attacks. Unarmed attacks deal 1d5 damage instead of 1.', prerequisites: ['Athletics'] },
    { name: 'Explosives', description: 'Knowledge of creating, handling, and disarming explosive devices.', effects: 'Allows Intellect checks to safely handle, place, or disarm explosives.', prerequisites: ['Chemistry'] },
    // Master
    { name: 'Sophontology', description: 'The study of the psychology of intelligent alien species.', effects: 'Grants Advantage on checks made to negotiate with or deceive intelligent alien life.', prerequisites: ['Psychology'] },
    { name: 'Exobiology', description: 'The study of extraterrestrial life forms.', effects: 'Allows for an Intellect check to determine an alien creature\'s weaknesses and abilities after a brief observation.', prerequisites: ['Genetics'] },
    { name: 'Surgery', description: 'The ability to perform complex medical operations.', effects: 'Allows an Intellect check to perform surgery, which can heal a Wound or install cybernetics.', prerequisites: ['Pathology'] },
    { name: 'Robotics', description: 'The design, construction, and operation of robots and drones.', effects: 'Allows you to build, modify, and repair robotic assistants.', prerequisites: ['Engineering'] },
    { name: 'Artificial Intelligence', description: 'The creation and understanding of simulated human consciousness.', effects: 'Allows you to create, interface with, or attempt to control true AIs.', prerequisites: ['Hacking'] },
    { name: 'Command', description: 'The ability to lead and inspire others in high-stress situations.', effects: 'Once per session, you can give an order that allows a crewmate to re-roll a failed Panic Check.', prerequisites: ['Vehicle Specialization', 'Tactics'] },
    { name: 'Hyperspace', description: 'Esoteric knowledge of the bizarre realities of faster-than-light travel.', effects: 'Grants Advantage on all checks related to surviving or navigating hyperspace anomalies.', prerequisites: ['Astrogation'] },
    { name: 'Xenoesotericism', description: 'Understanding of obscure alien mysticism, rituals, and their potential effects.', effects: 'Grants a chance to understand and possibly counteract alien curses or psychic attacks.', prerequisites: ['Mysticism'] },
    { name: 'Wilderness Survival', description: 'Mastery of surviving in hostile, alien environments.', effects: 'Grants Advantage on all checks related to finding food, water, and shelter on alien worlds.', prerequisites: ['Firearms'] },
    { name: 'Cybernetics', description: 'The art of interfacing biological beings with machines.', effects: 'Allows you to install, repair, and create cybernetic enhancements.', prerequisites: ['Jury-Rigging'] }
];


export const STARTING_EQUIPMENT_TABLES: Record<ClassName, string[]> = {
    'Marine': [
        "Tank Top and Camouflage Pants (PB 1), Combat Knife (like Scalpel, damage [+]), Stimulator (x5)",
        "Enhanced Armor Suit (PB 10), Flamethrower (4 charges), Boarding Axe",
        "Standard armor suit (PB 7), Combat shotgun (4 rounds), Backpack, Camping equipment",
        "Standard armor suit (PB 7), Pulse rifle (3 magazines), Infrared glasses",
        "Standard armor suit (PB 7), Smart rifle (3 magazines), Binoculars, Personal beacon",
        "Standard armor suit (PB 7), Submachine gun (3 magazines), Dry rations (x7)",
        "Field Uniform (PB 2), Combat Shotgun (2 rounds), Dog (pet), Leash, Tennis Ball",
        "Field uniform (PB 2), Revolver (12 rounds), Fragmentation grenade",
        "Dress Uniform (PB 1), Revolver (1 cartridge), Challenge Coin",
        "Enhanced armor suit (PB 10), Machine gun (1 box of cartridges), Tactical display"
    ],
    'Android': [
        "Spacesuit (PB 3), Smart Rifle (2 magazines), Infrared goggles, Mylar blanket",
        "Spacesuit (PB 3), Revolver (12 rounds), Long-range radio, Shoulder bag",
        "Protective suit (PB 5), Revolver (6 rounds), Defibrillator, First aid kit, Flashlight",
        "Protective suit (PB 5), Foam cannon (2 charges), Sample collection kit, Screwdriver (as Toolkit)",
        "Standard armor suit (PB 7), Tranquilizer gun (3 shots), Paracord (100 m)",
        "Crew Uniform (PB 1), Shock Baton, Small Pet (Organic)",
        "Crew Uniform (PB 1), Scalpel, Bioscanner",
        "Crew Uniform (PB 1), Fragmentation Grenade, Pocket Knife",
        "Special clothing (PB 1), Ticket for jump-9 (arrival port not filled)",
        "Corporate uniform (PB 1), Corporate card with VIP access"
    ],
    'Scientist': [
        "Protective suit (PB 5), Tranquilizer gun (3 shots), Bioscanner, Sample collection kit",
        "Protective suit (PB 5), Flamethrower (1 charge), Stimulator, Electronics tools",
        "Spacesuit (PB 3), Harpoon Gun, Sample Collection Kit, Flashlight, Lab Rat (Pet)",
        "Spacesuit (PB 3), Foam Cannon (2 charges), Folding Stretcher, First Aid Kit, Radiation Pills (x5)",
        "Lab Coat (PB 1), Screwdriver (as Toolkit), Medscanner, Vaccine (1 dose)",
        "Lab Coat (PB 1), Cybernetics Scanner, Portable Terminal",
        "Medical suit (PB 1), Scalpel, AutoMed (x5), Oxygen cylinder with filter mask",
        "Medical suit (PB 1), Ampule with acid, Mylar blanket, First aid kit",
        "Crew Uniform (PB 1), Stationery Knife (as Scalpel), Cybernetics Scanner, Duct Tape",
        "Civilian clothes (PB 1), Briefcase, Prescription form, Pen (poison injector)"
    ],
    'Teamster': [
        "Spacesuit (PB 3), Laser Cutter (1 extra battery), Patch Kit (x3), Belt with Tool Kit",
        "Spacesuit (PB 3), Revolver (6 rounds), Crowbar, Flashlight",
        "Spacesuit (PB 3), Harpoon gun (1 shot), Shovel, Rescue drone",
        "Chemical protection suit (PB 5), Vibration machete, Adjustable wrench, Camping equipment, Water filter",
        "Work clothes (PB 2), Explosives and Detonator, Cigarettes",
        "Work clothes (PB 2), Drill (as a Tool Kit), Paracord (100 m), Rescue drone",
        "Crew Uniform (PB 1), Combat Shotgun (4 rounds), Power Strip (20m), Cat (pet)",
        "Crew Uniform (PB 1), Nailgun (32 rounds), Headlamp, Belt with Tool Kit, Lunchbox",
        "Crew uniform (PB 1), Signal pistol (2 rounds), Water filter, Personal beacon, Ground penetrating radar",
        "Home clothes (PB 1), Crowbar, Stimulator, Six pack of beer"
    ]
};

export const TRINKETS = [
    "Guide \"PANIC: Harbinger of Disaster\"",
    "Antique Stocks (Asteroid Mine)",
    "Guide \"SURVIVAL: Eating Soup with a Knife\"",
    "Corn Husk Doll",
    "Herbarium from an unknown planet (regular)",
    "Necklace of bullet casings",
    "Rusty android processor",
    "Brochure \"Symptoms of Parasitic Infection\"",
    "Handle Your Rifle Like a Lady Guide",
    "Bone knife",
    "Aliens Pin-Up Calendar",
    "Rejected Application (Colonial Ship)",
    "Hologram of a serpentine dancer",
    "Whiskey with a snake",
    "Medical container with purple powder",
    "Cheap Viagra Pills",
    "Playing cards from the casino",
    "Rabbit's foot",
    "Moonstone Ring",
    "Guide to Ore Mining Safety",
    "Brochure \"No to human simulacra!\"",
    "Animal skull with 3 eyes and twisted horns",
    "Bartender Certificate (Expired)",
    "Bunraku doll",
    "Crumpled Camping Mug",
    "Creepy mask",
    "Absolutely black glass ball",
    "Ivory dice",
    "Tarot cards with gilded edge (worn)",
    "A bag of different teeth",
    "Ashes (of a relative)",
    "Pendant \"Do not resuscitate\"",
    "Cigarettes (with a grinning skull)",
    "Areca Nut Tablets",
    "Keychain: Shell fragments in plastic",
    "Zen and the Art of Load Placement Brochure",
    "A couple of shot glasses (spent shotgun shells)",
    "Key (Childhood Home)",
    "Army dog tag (family heirloom)",
    "Token: \"Is this your moral self-improvement?\"",
    "Flesh Relic Brochure",
    "Brochure \"Indifferent Stars\"",
    "Calendar \"Famous Battles\"",
    "Rich Captain Poor Captain Guide",
    "Propaganda poster (home planet)",
    "Pickled mutant insect",
    "Titanium toothpick",
    "Leather Gloves (from Xenomorph)",
    "Porn \"Captain's Order\" (anti-government)",
    "Towel, slightly worn",
    "Brass knuckles",
    "Fur handcuffs",
    "Diary of grievances",
    "Stylish cigarette case",
    "A ball of wires of different diameters",
    "Spanner",
    "Folding knife, decorative",
    "Xenomorph Horn Powder",
    "Pot with bonsai tree",
    "Golf club (putter)",
    "Fossilized trilobite",
    "Brochure \"A Mistress in Every Port\"",
    "Patched overalls with name tag",
    "A cloudy sealed jar containing a fleshy creature",
    "Bracelet with spikes",
    "Harmonica",
    "A porn magazine, tattered and read to holes",
    "Coffee mug with a chip and the inscription \"HAPPINESS IS A DUTY\"",
    "Guide \"Moonshine from gun oil and fuel\"",
    "Chess set made of bone, missing pieces",
    "Tin gyroscope, bent",
    "Faded green poker chip",
    "Ukulele",
    "Spray paint",
    "Wanted poster ruined by weather",
    "Hair Locket",
    "Golden Rat Statue",
    "Fireproof blanket",
    "Parka with hood and fleece lining",
    "Blowgun",
    "Flint hatchet",
    "Pendant: Two astronauts form a skull",
    "Rubik's cube",
    "Anti-stress toy with the inscription \"Zero stress in zero gravity\"",
    "First satellite badge",
    "Ushanka",
    "Grey Alien Mesh Cap",
    "Balm \"Zvezdochka\"",
    "Pith helmet",
    "Awning 10m x 10m",
    "The Book of Changes (without fortune-telling sticks)",
    "Kukri knife",
    "Sapper shovel",
    "Sharpening from a butter knife",
    "Stuffed cat",
    "Brochure \"Interpretation of sheep dreams\"",
    "A faded photo of a windy wasteland",
    "Opera glasses",
    "Brochure \"Android Overlords\"",
    "Interstellar compass points to home planet"
];

export const PATCHES = [
    "\"I'm certainly not an astrophysicist, but you're definitely an idiot!\"",
    "Medic's Patch (Skull and Crossbones on a Cross Background)",
    "Back patch \"Don't run, you'll die tired\"",
    "Red Shirt Logo_",
    "Blood type (matches the character)",
    "\"Do I LOOK like an expert?!\"",
    "Biohazard symbol",
    "Mr. Yuk_",
    "Radioactive hazard symbol",
    "\"Eat the rich\"_",
    "\"Don't hesitate, shoot twice\"",
    "Fire Emoji",
    "Smiley (glows in the dark)",
    "\"Smile, Big Brother is watching you\"",
    "Jolly Roger",
    "Viking Skull",
    "\"SUPER PREDATOR\" (saber-toothed tiger skull)",
    "Pin-up girl (ace of spades)",
    "Queen of Hearts",
    "Security",
    "\"LONER\"",
    "«Front Toward Enemy»_ (Claymore mine)",
    "Pin-up (Girl on a Rocket)",
    "FUBAR_",
    "\"I am a machine (of love)\"",
    "Pin-up girl (mechanic)",
    "\"HELLO, MY NAME IS:\"",
    "\"Soaked in coffee\"",
    "\"Take me to your leader\"_ (flying saucer)",
    "\"DO YOUR JOB\"",
    "\"Finish me, please.\"_",
    "\"Model Citizen\"",
    "\"I'm allergic to shit\" (medical style patch)",
    "\"Patch me first\" (caduceus)",
    "\"I like clean tools / and dirty girls\"",
    "\"The louder you scream, the sooner I'll finish\" (Pin-up Nurse)",
    "HMFIC (Head Mother Fucker In Charge)_",
    "Dove in the crosshairs",
    "Tibi Cthulhu",
    "\"Welcome to the DANGER ZONE\"_",
    "Skull and crossed wrenches",
    "Pin-up girl (succubus)",
    "\"DILLIGAF?\"__",
    "\"DRINK/FIGHT/LOVE\"",
    "\"Done the job / walk boldly\"",
    "Girl with a mudguard__",
    "Fun indicator (arrow at zero)",
    "\"GAME OVER\" (bride and groom)",
    "Heart",
    "\"IMPROVE / ADAPT / OVERCOME\"__",
    "\"SHUT UP AND BE PATIENT!\"",
    "\"Get Your act together, cowboy\" (crossed revolvers)",
    "\"Handyman\"",
    "NASA logo",
    "Crossed hammers with wings",
    "\"Keep it well lubricated\"",
    "Hammer and sickle",
    "\"5 for behavior\"",
    "\"Live free and die\"",
    "Back patch \"IF I RUNN - DON'T BE LEFT BEHIND\"",
    "\"Leather Bastard\"",
    "\"I am not a robot\"",
    "Red gear",
    "\"Stupidity cannot be cured\"",
    "\"Space is my home\" (sad astronaut)",
    "All-Seeing Eye",
    "«Solve Et Coagula»_ (baphomet)",
    "\"Nothing left to lose\" (astronaut with his pockets turned out)",
    "\"Travel to exotic, distant places / Encounter unusual things / Be eaten\"_",
    "BOHICA (Bend Over Here It Comes Again)__",
    "\"I am my brother's keeper\"_",
    "\"Mom tried\"",
    "Black widow (spider)",
    "\"I would ride your husband\"",
    "\"Universal Size\" (Grenade)",
    "Back patch: Death with a scythe",
    "Fuck off!",
    "\"Smooth Operator\"_",
    "Atom symbol",
    "\"In the name of science!\"",
    "\"Actually, I'm the scientist here.\"",
    "\"Help Wanted\"",
    "Princess",
    "\"NOMAD\"",
    "\"GOOD BOY\"",
    "Dice (two units)",
    "\"Employee of the Month\"",
    "\"Smart\" (brain)",
    "\"Bad girl\"",
    "\"Too beautiful to die\"",
    "\"Fuck to Death\" (Roses)",
    "Icarus",
    "\"A Girl's Best Friend\" (Diamond)",
    "High voltage symbol",
    "Inverted Cross",
    "Back patch \"Have you written me a check yet?\"",
    "\"I ♥ Myself\"",
    "Two cherries",
    "\"Volunteer\"",
    "Dead Man's Hand Cards (Black Aces and Eights)"
];

export const SHOP_ITEMS: ShopItem[] = [
    { name: 'Emergency beacon', price: 2000, description: 'A small device that produces a signal light and then a loud sound every few seconds. Additionally, it sends a distress signal by radio, but this can be jammed by a jammer.' },
    { name: 'Automed (x5)', price: 1500, description: 'Nanotech pills that help the body recover from damage. Gives an advantage in testing the body against diseases and poisons, as well as in attempts to restore health during rest.' },
    { name: 'First Aid Kit', price: 75, description: 'A set of bandages and medicines for stopping bleeding, dressing wounds and treating minor injuries.' },
    { name: 'Battery (high power)', price: 500, description: 'A reliable battery used to power laser cutters, rescue drones and other devices. Can be recharged in an hour from the mains or in 6 hours from the sun. Water protection is optional (+500 Kr).' },
    { name: 'Binoculars', price: 150, description: '20x magnification. Night vision (+300 Kr) or thermal vision (+1 kKr) can be added.' },
    { name: 'Bioscanner', price: 3000, description: "Long Range. Allows the user to search for signs of life. Can show the position of living organisms, but not their species. Blocked by materials of the caretaker's choice." },
    { name: 'Explosives and detonator', price: 500, description: 'An explosive charge powerful enough to destroy an airlock door. Any creature within range must make a Body saving throw or take damage (explosion) on a failed save. The detonator will work at long range, but can be blocked by a jammer.' },
    { name: 'Water filter', price: 50, description: 'Produces up to 4 liters of clean water per hour even from the dirtiest swamp.' },
    { name: 'Interference generator', price: 4000, description: 'The device is the size of a backpack. When turned on, it jams all radio signals within a radius of 100 km.' },
    { name: 'Tools for electronics', price: 100, description: 'A set of tools for assembling and repairing electronic devices.' },
    { name: 'Infrared glasses', price: 1500, description: 'Allows the wearer to see heat traces, sometimes even left several hours ago. Night vision can be added (+300 Cr).' },
    { name: 'Oxygen cylinder', price: 50, description: 'When installed on a spacesuit, it allows breathing for up to 12 hours under normal conditions or 4 hours under load. Explosive.' },
    { name: 'Sample collection kit', price: 50, description: 'Used to study xenoflora and xenofauna in the field. Can measure vital signs, take DNA samples, and gather other data on alien organisms. Results may not be immediate and may require a lab for full analysis.' },
    { name: 'Magnetic boots', price: 350, description: 'Provides the user with magnetic grip, allowing movement around the fuselage of a ship (in space, when docked, or in free flight), as well as metallic asteroids or other magnetic surfaces.' },
    { name: 'Mylar blanket', price: 10, description: 'A lightweight blanket made of heat-reflecting material. Often used to regulate the temperature of patients suffering from cold or other injuries.' },
    { name: 'Medscanner', price: 8000, description: 'Allows you to scan a living patient or a dead body for diseases and abnormalities without performing a biopsy or autopsy. Results may not be immediate and may require a lab for full analysis.' },
    { name: 'Mounting gear', price: 25, description: 'Grants advantage on Strength checks to open jammed gates, move heavy objects, etc.' },
    { name: 'Set of patches (x3)', price: 200, description: 'Repairs a punctured or torn spacesuit. Patched spacesuits have a PB of 1.' },
    { name: 'Toolkit', price: 20, description: 'Wrenches, adjustable wrenches, screwdrivers, etc. In extreme cases, they can be used as weapons (1d5 damage).' },
    { name: 'Set of lock picks', price: 40, description: 'An advanced set of tools for opening standard gateways and electronic locks.' },
    { name: 'Body camera', price: 50, description: 'A camera on your clothes that can transmit video to the control center so that others can see what you see. You can add night vision (+300 Kr) or thermal vision (+1 kKr).' },
    { name: 'Paracord (50 m)', price: 10, description: 'Lightweight general purpose nylon rope.' },
    { name: 'Personal beacon', price: 200, description: "Allows the crew to track the owner's position in the control center (or on the ship's bridge)." },
    { name: 'Pet (Organic)', price: 200000, description: 'A small or medium-sized organic animal. Large or rare pets are worth 2d10 times as much.' },
    { name: 'Pet (Synthetic)', price: 15000, description: 'A small or medium-sized synthetic animal. Large or rare pets cost 2d10 times as much.' },
    { name: 'Portable terminal', price: 1500, description: 'A flat panel display, keyboard and connector that allows you to hack computers and networks, as well as perform common work tasks.' },
    { name: 'Hiking kit', price: 1000, description: 'Tent, flask, primus stove, backpack, compass and sleeping bag.' },
    { name: 'Short range radio', price: 100, description: 'Provides communication in space (within reasonable limits) and on the surface within a few kilometers, but can be jammed by a jammer.' },
    { name: 'Long range radio', price: 1000, description: 'A backpack-sized communication device for communication between the ship and the surface.' },
    { name: 'Jetpack', price: 75000, description: 'Allows the wearer to fly to a height of 100 m and maintain a speed of up to 100 km/h for two hours when fully fueled. Deals 1d100 [+] damage upon destruction. Can be refueled for 200 Cr.' },
    { name: 'Rebreather', price: 500, description: 'Filters toxic air and allows you to breathe underwater for up to 20 minutes without surfacing. You can connect an oxygen tank.' },
    { name: 'Backpack', price: 50, description: 'Large, durable, waterproof backpack.' },
    { name: 'Cybernetics scanner', price: 2000, description: 'Allows androids and other cybernetic life forms to be scanned for physical or mental problems. Often mistrusted by androids.' },
    { name: 'Folding stretcher', price: 150, description: 'A portable stretcher that fits into a backpack. Allows the patient to be securely fastened for transportation to the treatment site. The size when unfolded is about 2 m.' },
    { name: 'Smart extension', price: 10000, description: 'Allows remote viewing, recording and control of ranged weapons, as well as +5 damage.' },
    { name: 'Rescue drone', price: 10000, description: "A radio-controlled drone. It requires a battery to operate. Both hands are required to control it. It can fly at an altitude of up to 450 meters and at a distance of up to 3 km from the operator. It works for up to two hours. It can record and transmit video. You can purchase and equip it with two of the following devices: binoculars, interference generator, Geiger counter, laser cutter, medical scanner, personal beacon, infrared glasses, emergency beacon, cybernetic scanner, bioscanner. It can carry up to 20-30 kg." },
    { name: 'Stimulant (per piece)', price: 1000, description: 'Cures cryosickness, reduces stress by 1, restores 1d10 hit points, and grants [+] to all rolls for 1d10 minutes. Roll 1d10. If the result is less than the number of doses taken in the last 24 hours, make a death saving throw.' },
    { name: 'Dry rations (x7)', price: 70, description: 'Individual food rations in lightweight packaging. Each contains enough food for one person for a day (does not include water).' },
    { name: 'Geiger counter', price: 20, description: 'Detects radiation and displays its level.' },
    { name: 'Radiation Pills (x5)', price: 200, description: 'Take 1d5 damage and reduce radiation levels by 1 for 2d10 minutes.' },
    { name: 'Tactical Head-Up Display (HUD)', price: 100, description: 'Often used by Marines, it allows the user to see through the body cameras of other squad members. Connects to the weapon via a smart extension.' },
    { name: 'Flashlight', price: 30, description: 'Handheld or shoulder mounted. Illuminates 10m in front of the owner.' },
    { name: 'Glowstick (x5)', price: 5, description: 'Disposable glow sticks that emit light within a radius of one meter.' },
    { name: 'Exoloader', price: 100000, description: 'An open mechanical exoskeleton used for carrying loads (up to 5000 kg). The loader claws inflict 1 wound. The operator can only be in the crew uniform or standard armor suit. A battery is required for operation (it lasts for 48 hours).' },
];
